#!/usr/bin/bash

echo -n "Remote user: "; read RUSR
echo -n "Remote storage address: "; read ADDR
echo -n "Remote storage folder: "; read RDIR
RDIR=${RDIR%\/}
DST="$RUSR@$ADDR:$RDIR"
echo $DST

declare -A VMDRVS
vmnames=$(virsh list --state-shutoff --name)

for VMNAME in $vmnames
do
  DRVSLIST=()
  DRVSLIST+=$(/usr/bin/virsh dumpxml --domain $VMNAME | grep "source file" | grep "qcow2" | sed "s/<source file='//g" | sed "s/\.qcow2.*/.qcow2/g")
  VMDRVS[$VMNAME]=$DRVSLIST
done

echo


for vmname in ${!VMDRVS[*]}
do
        for qcow2name in ${VMDRVS[$vmname]}
        do
                DESTINATION=$DST/$HOSTNAME/$(date "+%Y-%m-%d")/$vmname
                echo -e "\e[33m[$vmname]\e[0m"  $qcow2name  "\e[33m>>>\e[0m" $DESTINATION/$(basename $qcow2name)
                #rsync -Prvz $qcow2name $DESTINATION &&
                #echo " >>> DONE"
        done
done
